button_card_templates:
  !include_dir_merge_named tablet/templates

views:
  - title: Home
    type: custom:grid-layout
    background: center / cover no-repeat fixed url('/local/tablet/wallpaper.jpg')
    layout:
      grid-template-columns: 90px 162px 162px repeat(2, 120px) repeat(4, 90px)
      grid-template-rows: repeat(7, 90px)
      grid-template-areas: |
        "light  main      main      none1    none1     cctv    cctv    cctv    cctv"
        "light  main      main      none1    none1     cctv    cctv    cctv    cctv"
        "light  main      main      none1    none1     cctv    cctv    cctv    cctv"
        "light  weather   weather   none2    none2     tv      tv      av      av"
        "light  weather   weather   none2    none2     tv      tv      av      av"
        "light  route     dog       vacuum   vacuum    avcon   avcon   avcon   avcon"
        "light  route     dog       vacuum   vacuum    volume  volume  volume  volume"

    cards:
      !include_dir_merge_list tablet/cards
