base:
  styles:
    card:
      - border-radius: 16px
      - background-color: '#00000099'
      - border-width: 0
      - -webkit-backdrop-filter: blur(10px)
      - color: white
    label:
      - color: white
    name:
      - color: white
      - opacity: 0.8

fill_width:
  styles:
    card:
      - width: 100% 

height-1row:
  styles:
    card:
      - height: 82px

height-1-5-rows:
  styles:
    card:
      - height: 123px

height-2rows:
  styles:
    card:
      - height: 172px

height-3rows:
  styles:
    card:
      - height: 262px